version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name cicd-app --s3-location s3://test-cicd-artifact-0307/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src
